# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GamePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self, controller):
        self.controller = controller
        self.game = controller.game

    def sync(self):
         self.game = self.controller.game

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalFrame = QtWidgets.QFrame(self.centralwidget)
        self.horizontalFrame.setGeometry(QtCore.QRect(120, 130, 591, 221))
        self.horizontalFrame.setStyleSheet("background-color: #33658A;\n"
"padding: 1em;\n"
"border-radius: 15px;\n"
"")
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.playBtn_2 = QtWidgets.QPushButton(self.horizontalFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.playBtn_2.setFont(font)
        self.playBtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.playBtn_2.setStyleSheet("background-color: white;")
        self.playBtn_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\assets/rock.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playBtn_2.setIcon(icon)
        self.playBtn_2.setIconSize(QtCore.QSize(160, 160))
        self.playBtn_2.setObjectName("playBtn_2")
        self.horizontalLayout.addWidget(self.playBtn_2)
        self.playBtn_3 = QtWidgets.QPushButton(self.horizontalFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.playBtn_3.setFont(font)
        self.playBtn_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.playBtn_3.setStyleSheet("background-color: white;")
        self.playBtn_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\assets/paper.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playBtn_3.setIcon(icon1)
        self.playBtn_3.setIconSize(QtCore.QSize(160, 160))
        self.playBtn_3.setObjectName("playBtn_3")
        self.horizontalLayout.addWidget(self.playBtn_3)
        self.playBtn_4 = QtWidgets.QPushButton(self.horizontalFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.playBtn_4.setFont(font)
        self.playBtn_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.playBtn_4.setAutoFillBackground(False)
        self.playBtn_4.setStyleSheet("border-radius: 15px; overflow: hidden;\n"
"background-color: white;")
        self.playBtn_4.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\assets/scissors.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playBtn_4.setIcon(icon2)
        self.playBtn_4.setIconSize(QtCore.QSize(160, 160))
        self.playBtn_4.setObjectName("playBtn_4")
        self.horizontalLayout.addWidget(self.playBtn_4)
        self.nextRoundBtn = QtWidgets.QPushButton(self.centralwidget)
        self.nextRoundBtn.setGeometry(QtCore.QRect(300, 500, 231, 41))
        self.nextRoundBtn.setStyleSheet("font-size: 32px;\n"
"color: white;\n"
"background-color: #2F4858;\n"
"border-radius: 15px;\n"
"text-align: center;")
        self.nextRoundBtn.setObjectName("nextRoundBtn")
        self.userDisplay = QtWidgets.QLabel(self.centralwidget)
        self.userDisplay.setGeometry(QtCore.QRect(210, 360, 410, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.userDisplay.setFont(font)
        self.userDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.userDisplay.setObjectName("userDisplay")
        self.aiDisplay = QtWidgets.QLabel(self.centralwidget)
        self.aiDisplay.setGeometry(QtCore.QRect(210, 400, 410, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.aiDisplay.setFont(font)
        self.aiDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.aiDisplay.setObjectName("aiDisplay")
        self.winnerLabel = QtWidgets.QLabel(self.centralwidget)
        self.winnerLabel.setGeometry(QtCore.QRect(120, 440, 591, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.winnerLabel.setFont(font)
        self.winnerLabel.setStyleSheet("color: white;\n"
"border-radius: 15px;\n"
"background-color:  #F26419;")
        self.winnerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.winnerLabel.setObjectName("winnerLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(120, 30, 581, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scoreLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.scoreLabel.setFont(font)
        self.scoreLabel.setObjectName("scoreLabel")
        self.horizontalLayout_2.addWidget(self.scoreLabel)
        self.roundLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.roundLabel.setFont(font)
        self.roundLabel.setObjectName("roundLabel")
        self.horizontalLayout_2.addWidget(self.roundLabel)
        self.exitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exitBtn.setGeometry(QtCore.QRect(20, 20, 50, 50))
        self.exitBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exitBtn.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.exitBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\assets/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitBtn.setIcon(icon3)
        self.exitBtn.setIconSize(QtCore.QSize(50, 50))
        self.exitBtn.setObjectName("exitBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.controller.update_game.connect(self.sync)

        def hide_all():
            self.userDisplay.setVisible(False)
            self.aiDisplay.setVisible(False)
            self.winnerLabel.setVisible(False)
            self.nextRoundBtn.setVisible(False)

        def set_text(user, ai, winner):
            self.userDisplay.setText(f"{self.controller.player_name} chose: {user}")
            self.aiDisplay.setText(f"Computer chose: {ai}")
            self.winnerLabel.setText(winner)

        def push_log(name, variant, against):
            self.game.log.append({ 
                        "name" : name,
                        "type" : variant,
                        "against" : against
                    })
        def check_winner():
            if self.game.plr_wins > self.game.ai_wins:
                    self.controller.log.append({
                        "plr1" : self.controller.player_name,
                        "plr2" : "Computer",
                        "winner" : "Player 1"
                    })
            elif self.game.plr_wins < self.game.ai_wins:
                    self.controller.log.append({
                        "plr1" : self.controller.player_name,
                        "plr2" : "Computer",
                        "winner" : "Player 2"
                    })
            else:
                    self.controller.log.append({
                        "plr1" : self.controller.player_name,
                        "plr2" : "Computer",
                        "winner" : "Draw"
                    })
        
        def forfeit():
            if self.game.cur_rounds == self.controller.rounds:
                check_winner()
            else:
                self.controller.log.append({
                    "plr1" : self.controller.player_name,
                    "plr2" : "Computer",
                    "winner" : "Player 2"
                })
            self.controller.set_window(0)
            

        def click(choice):
                if self.game.debounce: return
                choice2 = self.game.get_rand()
                winner = self.game.determine_winner(choice, choice2)
                self.userDisplay.setVisible(True)
                self.aiDisplay.setVisible(True)
                self.winnerLabel.setVisible(True)
                self.nextRoundBtn.setVisible(True)
                if winner == 0:
                    set_text(choice, choice2, "You won!")
                    push_log(self.controller.player_name, "Win", "Computer")
                elif winner == 1:
                    set_text(choice, choice2, "You Lost!")
                    push_log(self.controller.player_name, "Loss", "Computer")
                elif winner == 2:
                    set_text(choice, choice2, "It was a draw!!")
                    push_log(self.controller.player_name, "Draw", "Computer")
                self.scoreLabel.setText(f"Score: {self.game.plr_wins}-{self.game.ai_wins}")
                self.roundLabel.setText(f"Round: {(self.controller.rounds - self.game.cur_rounds)+1}")
                self.game.debounce = True


        def next_round_click():
            self.game.advance_round()
            self.game.debounce = False
            if self.game.over:
                self.controller.set_window(0)
                check_winner()
                self.controller.new_game()
                self.game = self.controller.game
            hide_all()

        hide_all()

        self.playBtn_2.clicked.connect(lambda : click("rock"))
        self.playBtn_3.clicked.connect(lambda : click("paper"))
        self.playBtn_4.clicked.connect(lambda : click("scissors"))
        self.nextRoundBtn.clicked.connect(next_round_click)
        self.exitBtn.clicked.connect(forfeit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nextRoundBtn.setText(_translate("MainWindow", "Next Round >"))
        self.userDisplay.setText(_translate("MainWindow", "User"))
        self.aiDisplay.setText(_translate("MainWindow", "AI"))
        self.winnerLabel.setText(_translate("MainWindow", "Winner"))
        self.scoreLabel.setText(_translate("MainWindow", "Score: 0-0"))
        self.roundLabel.setText(_translate("MainWindow", "Round: 1"))
