# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GamePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from Game import Game
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self, controller):
        self.controller = controller
        self.game = Game(self.controller)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalFrame = QtWidgets.QFrame(self.centralwidget)
        self.horizontalFrame.setGeometry(QtCore.QRect(110, 120, 591, 221))
        self.horizontalFrame.setStyleSheet("background-color: #33658A;\n"
"padding: 1em;\n"
"border-radius: 15px;\n"
"")
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.playBtn_2 = QtWidgets.QPushButton(self.horizontalFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.playBtn_2.setFont(font)
        self.playBtn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.playBtn_2.setStyleSheet("background-color: white;")
        self.playBtn_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\assets/rock.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playBtn_2.setIcon(icon)
        self.playBtn_2.setIconSize(QtCore.QSize(250, 250))
        self.playBtn_2.setObjectName("playBtn_2")
        self.horizontalLayout.addWidget(self.playBtn_2)
        self.playBtn_3 = QtWidgets.QPushButton(self.horizontalFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.playBtn_3.setFont(font)
        self.playBtn_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.playBtn_3.setStyleSheet("background-color: #c7c0b2;")
        self.playBtn_3.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\assets/paper.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playBtn_3.setIcon(icon1)
        self.playBtn_3.setIconSize(QtCore.QSize(250, 250))
        self.playBtn_3.setObjectName("playBtn_3")
        self.horizontalLayout.addWidget(self.playBtn_3)
        self.playBtn_4 = QtWidgets.QPushButton(self.horizontalFrame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.playBtn_4.setFont(font)
        self.playBtn_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.playBtn_4.setAutoFillBackground(False)
        self.playBtn_4.setStyleSheet("border-radius: 15px; overflow: hidden;\n"
"background-color: white;")
        self.playBtn_4.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\assets/scissors.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playBtn_4.setIcon(icon2)
        self.playBtn_4.setIconSize(QtCore.QSize(200, 200))
        self.playBtn_4.setObjectName("playBtn_4")
        self.horizontalLayout.addWidget(self.playBtn_4)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 50, 461, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setPixmap(QtGui.QPixmap(".\\assets/plank_bg.jpg"))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.nextRoundBtn = QtWidgets.QPushButton(self.centralwidget)
        self.nextRoundBtn.setGeometry(QtCore.QRect(300, 490, 181, 41))
        self.nextRoundBtn.setStyleSheet("font-size: 32px;\n"
"color: white;\n"
"background-color: #2F4858;\n"
"border-radius: 15px;\n"
"text-align: left;")
        self.nextRoundBtn.setObjectName("nextRoundBtn")
        self.userDisplay = QtWidgets.QLabel(self.centralwidget)
        self.userDisplay.setGeometry(QtCore.QRect(310, 350, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.userDisplay.setFont(font)
        self.userDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.userDisplay.setObjectName("userDisplay")
        self.aiDisplay = QtWidgets.QLabel(self.centralwidget)
        self.aiDisplay.setGeometry(QtCore.QRect(310, 390, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.aiDisplay.setFont(font)
        self.aiDisplay.setAlignment(QtCore.Qt.AlignCenter)
        self.aiDisplay.setObjectName("aiDisplay")
        self.winnerLabel = QtWidgets.QLabel(self.centralwidget)
        self.winnerLabel.setGeometry(QtCore.QRect(110, 440, 591, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setItalic(True)
        self.winnerLabel.setFont(font)
        self.winnerLabel.setStyleSheet("color: white;\n"
"border-radius: 15px;\n"
"background-color:  #F26419;")
        self.winnerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.winnerLabel.setObjectName("winnerLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        def hide_all():
            self.userDisplay.setVisible(False)
            self.aiDisplay.setVisible(False)
            self.winnerLabel.setVisible(False)
            self.nextRoundBtn.setVisible(False)

        def click(choice):
                self.game.determine_winner(choice)
                self.userDisplay.setVisible(True)
                self.aiDisplay.setVisible(True)
                self.winnerLabel.setVisible(True)
                self.nextRoundBtn.setVisible(True)

        def next_round_click():
            self.game.advance_round()
            if self.game.over:
                self.controller.set_window(0)
            hide_all()

        hide_all()

        self.playBtn_2.clicked.connect(lambda : click("rock"))
        self.playBtn_3.clicked.connect(lambda : click("paper"))
        self.playBtn_4.clicked.connect(lambda : click("scissors"))
        self.nextRoundBtn.clicked.connect(next_round_click)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Choose Strategically..."))
        self.nextRoundBtn.setText(_translate("MainWindow", "Next Round >"))
        self.userDisplay.setText(_translate("MainWindow", "User"))
        self.aiDisplay.setText(_translate("MainWindow", "AI"))
        self.winnerLabel.setText(_translate("MainWindow", "Winner"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
