# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    
    def __init__(self, controller):
        self.controller = controller
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: white;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 711, 131))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("font-weight: bold;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 190, 701, 311))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(50)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.playBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.playBtn.setFont(font)
        self.playBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.playBtn.setStyleSheet("font-size: 32px;\n"
"color: white;\n"
"background-color: #33658A;\n"
"border-radius: 15px;\n"
"text-align: left;\n"
"padding-left: 1em;\n"
"")
        self.playBtn.setObjectName("playBtn")
        self.verticalLayout.addWidget(self.playBtn)
        self.settingsBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.settingsBtn.setMinimumSize(QtCore.QSize(300, 0))
        self.settingsBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.settingsBtn.setFont(font)
        self.settingsBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.settingsBtn.setStyleSheet("font-size: 32px;\n"
"color: white;\n"
"background-color: #2F4858;\n"
"border-radius: 15px;\n"
"text-align: left;\n"
"padding-left: 1em;\n"
"")
        self.settingsBtn.setObjectName("settingsBtn")
        self.verticalLayout.addWidget(self.settingsBtn)
        self.statsBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.statsBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.statsBtn.setFont(font)
        self.statsBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.statsBtn.setStyleSheet("font-size: 32px;\n"
"color: white;\n"
"background-color: #F6AE2D;\n"
"border-radius: 15px;\n"
"text-align: left;\n"
"padding-left: 1em;\n"
"")
        self.statsBtn.setObjectName("statsBtn")
        self.verticalLayout.addWidget(self.statsBtn)
        self.exitBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.exitBtn.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(-1)
        self.exitBtn.setFont(font)
        self.exitBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exitBtn.setAutoFillBackground(False)
        self.exitBtn.setStyleSheet("font-size: 32px;\n"
"color: white;\n"
"background-color: #F26419;\n"
"border-radius: 15px;\n"
"text-align: left;\n"
"padding-left: 1em;\n"
"")
        self.exitBtn.setObjectName("exitBtn")
        self.verticalLayout.addWidget(self.exitBtn)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("assets/background.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.playBtn.clicked.connect(lambda : self.controller.set_window(1))
        self.settingsBtn.clicked.connect(lambda : self.controller.set_window(2))
        self.statsBtn.clicked.connect(lambda : self.controller.set_window(3))
        self.exitBtn.clicked.connect(lambda : self.controller.exit())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Rock, Paper, Scissors"))
        self.playBtn.setText(_translate("MainWindow", "Play"))
        self.settingsBtn.setText(_translate("MainWindow", "Settings"))
        self.statsBtn.setText(_translate("MainWindow", "Stats"))
        self.exitBtn.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
