# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\SettingsPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self, controller):
        self.controller = controller
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(20)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 70, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(330, 430, 171, 41))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("font-size: 32px;\n"
"color: white;\n"
"background-color: #F26419;\n"
"border-radius: 15px;\n"
"text-align: center;")
        self.pushButton.setObjectName("pushButton")
        self.verticalFrame = QtWidgets.QFrame(self.centralwidget)
        self.verticalFrame.setGeometry(QtCore.QRect(200, 150, 441, 231))
        self.verticalFrame.setStyleSheet("background-color: #33658A;\n"
"border-radius: 15px;\n"
"box-sizing: border-box;")
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;\n"
"margin-left: 10px;\n"
"margin-right: 10px;")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.nameInput = QtWidgets.QLineEdit(self.verticalFrame)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.nameInput.setFont(font)
        self.nameInput.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.nameInput.setStyleSheet("background-color: white;\n"
"margin-left: 10px;\n"
"margin-right: 10px;\n"
"")
        self.nameInput.setText("")
        self.nameInput.setObjectName("nameInput")
        self.verticalLayout.addWidget(self.nameInput)
        self.label_3 = QtWidgets.QLabel(self.verticalFrame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white;\n"
"margin-left: 10px;\n"
"margin-right: 10px;")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.roundsInput = QtWidgets.QLineEdit(self.verticalFrame)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.roundsInput.setFont(font)
        self.roundsInput.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.roundsInput.setStyleSheet("background-color: white;\n"
"margin-left: 10px;\n"
"margin-right: 10px;\n"
"margin-bottom: 15px;")
        self.roundsInput.setObjectName("roundsInput")
        self.verticalLayout.addWidget(self.roundsInput)
        self.exitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exitBtn.setGeometry(QtCore.QRect(20, 20, 50, 50))
        self.exitBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exitBtn.setStyleSheet("background-color: rgba(0,0,0,0);")
        self.exitBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\assets/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exitBtn.setIcon(icon)
        self.exitBtn.setIconSize(QtCore.QSize(50, 50))
        self.exitBtn.setObjectName("exitBtn")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 20, 591, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: red;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 43))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.label_4.setVisible(False)

        def err_message(message):
            self.label_4.setVisible(True)
            self.label_4.setText(message)

        def submit():
            new_name = self.nameInput.text()
            new_rounds = self.roundsInput.text()

            # Validate
            if not new_rounds.isdigit():
                return err_message("Invalid Input for Rounds.")
            
            new_rounds = int(new_rounds)
            
            if new_rounds < 3 or new_rounds > 20:
                return err_message("Rounds must be between 3-20.")

            if len(new_name) <= 3 or len(new_name) > 20:
                return err_message("Name must be between 4-20 characters long.")
            
            self.controller.rounds = new_rounds
            self.controller.player_name = new_name

            self.label_4.setVisible(False)
            self.controller.set_window(0)


        self.pushButton.clicked.connect(submit)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Settings"))
        self.pushButton.setText(_translate("MainWindow", "Update"))
        self.label_2.setText(_translate("MainWindow", "Name:"))
        self.label_3.setText(_translate("MainWindow", "Rounds:"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
